<?php

namespace Database\Seeders\Shop;

use App\Models\Shop\Attribute;
use Illuminate\Database\Seeder;
use App\Enums\ShopAttributeType;

class AttributesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $attributes = [
            [
                'name:ar'         => 'رقم المنتج',
                'name:en'         => 'SKU',
                'code'            => 'sku',
                'type'            => ShopAttributeType::TEXT,
                'is_required'     => true,
                'is_filterable'   => false,
                'is_comparable'   => false,
                'is_user_defined' => false,
            ],
            [
                'code'            => 'name',
                'name:en'         => 'Name',
                'name:ar'         => 'الاسم',
                'type'            => ShopAttributeType::TEXT,
                'position'        => '3',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '1',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'status',
                'name:en'         => 'Status',
                'name:ar'         => 'الحالة',
                'type'            => ShopAttributeType::BOOLEAN,
                'position'        => '10',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'short_description',
                'name:en'         => 'Short Description',
                'name:ar'         => 'وصف مختصر',
                'type'            => ShopAttributeType::TEXTAREA,
                'position'        => '11',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'description',
                'name:en'         => 'Description',
                'name:ar'         => 'الوصف',
                'type'            => ShopAttributeType::TEXTAREA,
                'position'        => '12',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '1',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'price',
                'name:en'         => 'Price',
                'name:ar'         => 'السعر',
                'type'            => ShopAttributeType::PRICE,
                'position'        => '13',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '1',
                'is_comparable'   => '1',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'cost',
                'name:en'         => 'Cost',
                'name:ar'         => 'التكلفة',
                'type'            => ShopAttributeType::PRICE,
                'position'        => '14',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'special_price',
                'name:en'         => 'Special Price',
                'name:ar'         => 'سعر خاص',
                'type'            => ShopAttributeType::PRICE,
                'position'        => '15',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'special_price_from',
                'name:en'         => 'Special Price From',
                'name:ar'         => 'سعر خاص ابتداءًا من',
                'type'            => ShopAttributeType::DATE,
                'position'        => '16',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'special_price_to',
                'name:en'         => 'Special Price To',
                'name:ar'         => 'سعر خاص حتى',
                'type'            => ShopAttributeType::DATE,
                'position'        => '17',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'meta_title',
                'name:en'         => 'Meta Title',
                'name:ar'         => 'العنوان',
                'type'            => ShopAttributeType::TEXTAREA,
                'position'        => '18',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'meta_keywords',
                'name:en'         => 'Meta Keywords',
                'name:ar'         => 'الكلمات المفتاحية',
                'type'            => ShopAttributeType::TEXTAREA,
                'position'        => '20',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'meta_description',
                'name:en'         => 'Meta Description',
                'name:ar'         => 'الوصف',
                'type'            => ShopAttributeType::TEXTAREA,
                'position'        => '21',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'length',
                'name:en'         => 'Length',
                'name:ar'         => 'الطول',
                'type'            => ShopAttributeType::TEXT,
                'position'        => '22',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'width',
                'name:en'         => 'Width',
                'name:ar'         => 'العرض',
                'type'            => ShopAttributeType::TEXT,
                'position'        => '23',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'height',
                'name:en'         => 'Height',
                'name:ar'         => 'الارتفاع',
                'type'            => ShopAttributeType::TEXT,
                'position'        => '24',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'weight',
                'name:en'         => 'Weight',
                'name:ar'         => 'الوزن',
                'type'            => ShopAttributeType::TEXT,
                'position'        => '25',
                'is_required'     => true,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'color',
                'name:en'         => 'Color',
                'name:ar'         => 'اللون',
                'type'            => ShopAttributeType::SELECT,
                'position'        => '26',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '1',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'size',
                'name:en'         => 'Size',
                'name:ar'         => 'المقاس',
                'type'            => ShopAttributeType::SELECT,
                'position'        => '27',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '1',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'brand',
                'name:en'         => 'Brand',
                'name:ar'         => 'العلامة التجارية',
                'type'            => ShopAttributeType::SELECT,
                'position'        => '28',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '1',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'new',
                'name:en'         => 'New',
                'name:ar'         => 'New',
                'type'            => ShopAttributeType::BOOLEAN,
                'position'        => '6',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
            [
                'code'            => 'featured',
                'name:en'         => 'Featured',
                'name:ar'         => 'Featured',
                'type'            => ShopAttributeType::BOOLEAN,
                'position'        => '7',
                'is_required'     => false,
                'is_unique'       => '0',
                'is_filterable'   => '0',
                'is_comparable'   => '0',
                'is_user_defined' => false,
            ],
        ];

        foreach ($attributes as $attribute) {
            Attribute::create($attribute);
        }
    }
}
